(define (problem surprising-task)
  (:domain dora-surprise)

  
  ;; IJCAI-2011 map according to Marc Han
  (:objects  cereal - visualobject
           Dora - robot
           place_0 place_1 place_2 place_3 place_4 place_5 place_6 place_7 - place 
	   
	   room1 room2 room3 room5 room6- room

	   living_room kitchen corridor office doorway other - category

	   

)

  (:init  
   
   ;; Topology
   (connected 0 1)
   (connected 1 2)
   (connected 2 3)
   (connected 3 4)
   (connected 4 5)
   (connected 5 6)
   (connected 6 7)

   ;; Categorical

   (= (category room5) doorway)
   (= (category room6) doorway)
   
   ;; Suppose that
   ;;
   ;; 0.8 "cereal" (the object) is in Kitchens
   ;; 0.9 cups are in living rooms

   (probabilistic 0.95 (and (= (category room1) living_room)
			    (probabilistic 0.76 (and (= (category room2) corridor)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     ) 
					   0.06 (and (= (category room2) office)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   0.06 (and (= (category room2) living_room)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   0.06 (and (= (category room2) kitchen)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   0.06 (and (= (category room2) other)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   )
			    ) 
		  0.25 (and (= (category room1) office)
			    (probabilistic 0.76 (and (= (category room2) corridor)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     ) 
					   0.06 (and (= (category room2) office)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   0.06 (and (= (category room2) living_room)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   0.06 (and (= (category room2) kitchen)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   0.06 (and (= (category room2) other)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   )
			    ) )
		  0.25 (and (= (category room1) corridor)
			    (probabilistic 0.76 (and (= (category room2) corridor)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     ) 
					   0.06 (and (= (category room2) office)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   0.06 (and (= (category room2) living_room)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   0.06 (and (= (category room2) kitchen)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   0.06 (and (= (category room2) other)
						     (probabilistic 0.2 (and (= (category room3) corridor)) 
								    0.2 (and (= (category room3) office))
								    0.2 (and (= (category room3) living_room))
								    0.2 (and (= (category room3) kitchen))
								    0.2 (and (= (category room3) other)))
						     )
					   )
			    ) 
		  )
  )